name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create wrangler.toml from template
        run: |
          cp wrangler.example.toml wrangler.toml
          sed -i "s|your-api-base-url|${{ secrets.TICKER_API_BASE_URL }}|g" wrangler.toml
          sed -i "s|your-api-key|${{ secrets.TICKER_API_KEY }}|g" wrangler.toml

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: production
          
      - name: Test deployment
        run: |
          # Wait for deployment to propagate
          sleep 10
          
          # Test health endpoint (replace with your worker URL after first deployment)
          # curl -f https://ticker-backend-worker.your-subdomain.workers.dev/health || echo "Health check failed - worker might still be starting"